
<!-- PITCHER_START -->

# langu

![Type](https://pitcherprobadges.onrender.com/api/badge?label=Type&value=Frontend%20Web%20Application&color=a855f7&labelColor=334155&style=for-the-badge) ![Files](https://pitcherprobadges.onrender.com/api/badge?label=Files&value=4&color=f97316&labelColor=334155&style=for-the-badge) ![Lines of Code](https://pitcherprobadges.onrender.com/api/badge?label=LOC&value=1613&color=22c55e&labelColor=334155&style=for-the-badge)

![HTML5](https://img.shields.io/badge/HTML5-E34F26?style=for-the-badge&logo=html5&logoColor=white) ![CSS3](https://img.shields.io/badge/CSS3-1572B6?style=for-the-badge&logo=css3&logoColor=white) ![JavaScript](https://img.shields.io/badge/JavaScript-F7DF1E?style=for-the-badge&logo=javascript&logoColor=black)

---

## Overview

**langu** is a **Frontend Web Application** built using **HTML, CSS, JavaScript**. The codebase comprises **4 source files** totaling **1,613 lines of code**.

---

## Preview

> **How to add Project Previews:**
    > 1. Create an `assets/` or `screenshots/` folder in your project root.
    > 2. Add your screenshots or demo GIFs (e.g., `assets/preview-1.png`, `assets/ui-2.png`).
    > 3. Save any file — PitcherPro will automatically detect all images in numeric order and render previews with captions!

---

##    Prerequisites

Make sure you have the following ready:

- **Modern Web Browser**: Google Chrome, Mozilla Firefox, Microsoft Edge, or Safari
- **Code Editor**: [VS Code](https://code.visualstudio.com/) (Recommended)
- **VS Code Extension**: [Live Server](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer) (Optional, for live preview)

---

##   Installation Guide

Follow these simple steps to set up the project locally:

1. **Clone the repository:**
   ```bash
   git clone <repository-url>
   cd langu
   ```

2. **Open the project in VS Code:**
   ```bash
   code .
   ```

3. **No package installation required.** You can launch directly via Live Server or open `index.html` in any modern browser.

---

##  How to Run

### Option 1: Direct Browser
Double click on `index.html` file to open it directly in any browser.

### Option 2: Live Server (VS Code)
1. Open project in VS Code (`code .`).
2. Right click on `index.html`.
3. Click on **"Open with Live Server"**.

---

## Technology Stack

- HTML
- CSS
- JavaScript

---

## Folder Structure

```text
langu/
├── app.js (20.7 KB)
├── index.html (6.4 KB)
├── README.md (3.1 KB)
└── style.css (11.2 KB)
```

---

## Project Statistics

- **Total Files & Folders:** **4** files in **0** folders
- **Project Size:** **41.3 KB** 
- **Source Code (LOC):** 1,613 lines
- **Code Composition:** 55.9% Code • 4.6% Comments • 39.5% Blanks
- **File Extensions:** `.js` (1) • `.html` (1) • `.md` (1) • `.css` (1)

### Key Files & Sizes
- `app.js` — **20.7 KB** (821 lines)
- `style.css` — **11.2 KB** (546 lines)
- `index.html` — **6.4 KB** (246 lines)
- `README.md` — **3.1 KB** (72 lines)


---

## Author

**Author:** Himanshu   
Last Updated: 24 / 09 / 2026 at 02:01 AM  
Documentation generated by [PitcherPro](https://sefard01.github.io/pitcherProweb/)


<!-- PITCHER_END -->
